### ISSUE TITLE
Unable to find USB

### ISSUE THREAD

**Issue by ghost** [braiden/python-ant-downloader#63]
Hello,

I have an odd USB device in th fact that lsusb shows it to be

ID 0fcf:1004 Dynastream Innovations, Inc. ANT2USB

rather than 0fcf:1008

I think this is causing an issue where I get the following

[MainThread]    2014-09-06 14:26:24,122 WARNING Failed to find Garmin nRF24AP2 (newer) USB Stick.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/antd/cfg.py", line 92, in create_hardware
    return hw.UsbHardware(id_vendor, id_product, bulk_endpoint)
  File "/usr/local/lib/python2.7/dist-packages/antd/hw.py", line 61, in **init**
    raise NoUsbHardwareFound(errno.ENOENT, "No available device matching vid(0x%04x) pid(0x%04x)." % (id_vendor, id_product))
NoUsbHardwareFound: [Errno 2] No available device matching vid(0x0fcf) pid(0x1008).

Is there any way the code can be a little more flexible to accommodate my differently named USB stick?

Thanks

**Comment by tomhumphrey** [comment]
I have ID 0fcf:1009. Did you manage to fix this? I'm trying to sync a Garmin Swim

**Comment by StephenHodge** [comment]
Hi having the same error of NRF24AP2 also for my Garmin Swim either of you have any joy?
